# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  dataprep:
    build:
      context: GenAIComps
      dockerfile: comps/dataprep/src/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
  embedding:
    build:
      context: GenAIComps
      dockerfile: comps/embeddings/src/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${REGISTRY:-opea}/embedding:${TAG:-latest}
  retriever:
    build:
      context: GenAIComps
      dockerfile: comps/retrievers/src/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${REGISTRY:-opea}/retriever:${TAG:-latest}
  reranking:
    build:
      context: GenAIComps
      dockerfile: comps/rerankings/src/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${REGISTRY:-opea}/reranking:${TAG:-latest}
  doc-index-retriever:
    build:
      context: ../../DocIndexRetriever
      dockerfile: ./Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${REGISTRY:-opea}/doc-index-retriever:${TAG:-latest}
  agent:
    build:
      context: GenAIComps
      dockerfile: comps/agent/src/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${REGISTRY:-opea}/agent:${TAG:-latest}
  agent-ui:
    build:
      context: ../ui
      dockerfile: ./docker/Dockerfile
    extends: agent
    image: ${REGISTRY:-opea}/agent-ui:${TAG:-latest}
  vllm-rocm:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      context: ../
      dockerfile: ./Dockerfile-vllm-rocm
    image: ${REGISTRY:-opea}/llm-vllm-rocm:${TAG:-latest}
