# Copyright (C) 2024 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0

services:
  faqgen-vllm-service:
    image: ${REGISTRY:-opea}/llm-vllm-rocm:${TAG:-latest}
    container_name: faqgen-vllm-service
    ports:
      - "${FAQGEN_VLLM_SERVICE_PORT:-8081}:8011"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${FAQGEN_HUGGINGFACEHUB_API_TOKEN}
      HF_TOKEN: ${FAQGEN_HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      WILM_USE_TRITON_FLASH_ATTENTION: 0
      PYTORCH_JIT: 0
    volumes:
      - "./data:/data"
    shm_size: 20G
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/:/dev/dri/
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
      - apparmor=unconfined
    command: "--model ${FAQGEN_LLM_MODEL_ID} --swap-space 16 --disable-log-requests --dtype float16 --tensor-parallel-size 4 --host 0.0.0.0 --port 8011 --num-scheduler-steps 1 --distributed-executor-backend \"mp\""
    ipc: host

  faqgen-llm-server:
    image: ${REGISTRY:-opea}/llm-faqgen:${TAG:-latest}
    container_name: faqgen-llm-server
    depends_on:
      - faqgen-vllm-service
    ports:
      - "${FAQGEN_LLM_SERVER_PORT:-9000}:9000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_ENDPOINT: ${FAGGEN_LLM_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${FAQGEN_HUGGINGFACEHUB_API_TOKEN}
      HUGGING_FACE_HUB_TOKEN: ${FAQGEN_HUGGINGFACEHUB_API_TOKEN}
      LLM_MODEL_ID: ${FAQGEN_LLM_MODEL_ID}
      FAQGen_COMPONENT_NAME: "OpeaFaqGenvLLM"
      LOGFLAG: ${LOGFLAG:-False}
    restart: unless-stopped

  faqgen-backend-server:
    image: ${REGISTRY:-opea}/faqgen:${TAG:-latest}
    container_name: faqgen-backend-server
    depends_on:
      - faqgen-vllm-service
      - faqgen-llm-server
    ports:
      - "${FAQGEN_BACKEND_SERVER_PORT:-8888}:8888"
    environment:
      no_proxy: ${no_proxy}
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
      MEGA_SERVICE_HOST_IP: ${HOST_IP}
      LLM_SERVICE_HOST_IP: ${HOST_IP}
      LLM_SERVICE_PORT: ${FAQGEN_LLM_SERVER_PORT}
    ipc: host
    restart: always
  faqgen-ui-server:
    image: ${REGISTRY:-opea}/faqgen-ui:${TAG:-latest}
    container_name: faqgen-ui-server
    depends_on:
      - faqgen-backend-server
    ports:
      - "${FAGGEN_UI_PORT:-5173}:5173"
    environment:
      no_proxy: ${no_proxy}
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
      FAQ_BASE_URL: ${FAQGEN_BACKEND_ENDPOINT}
    ipc: host
    restart: always
networks:
  default:
    driver: bridge
