services:
  videoqna-vdms-vector-db:
    image: intellabs/vdms:v2.8.0
    container_name: videoqna-vdms-vector-db
    ports:
      - "8001:55555"
  videoqna-dataprep:
    image: ${REGISTRY:-opea}/dataprep-multimodal-vdms:${TAG:-latest}
    container_name: videoqna-dataprep-vdms-server
    depends_on:
      - videoqna-vdms-vector-db
    ports:
      - "6007:6007"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      VDMS_HOST: ${VDMS_HOST}
      VDMS_PORT: ${VDMS_PORT}
      INDEX_NAME: ${INDEX_NAME}
    entrypoint: sh -c 'sleep 15 && python ingest_videos.py'
    volumes:
      - /home/$USER/.cache/clip:/home/user/.cache/clip
      - /home/$USER/.cache/huggingface/hub:/home/user/.cache/huggingface/hub
  videoqna-embedding:
    image: ${REGISTRY:-opea}/embedding-multimodal-clip:${TAG:-latest}
    container_name: videoqna-embedding-multimodal-server
    ports:
      - "6000:6000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    volumes:
      - /home/$USER/.cache/huggingface/hub:/home/user/.cache/huggingface/hub
    restart: unless-stopped
  videoqna-retriever:
    image: ${REGISTRY:-opea}/retriever-vdms:${TAG:-latest}
    container_name: videoqna-retriever-vdms-server
    depends_on:
      - videoqna-vdms-vector-db
    ports:
      - "7000:7000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      INDEX_NAME: ${INDEX_NAME}
      VDMS_HOST: ${VDMS_HOST}
      VDMS_PORT: ${VDMS_PORT}
      USECLIP: ${USECLIP}
    entrypoint: sh -c 'sleep 30 && python retriever_vdms.py'
    restart: unless-stopped
    volumes:
      - /home/$USER/.cache/huggingface/hub:/home/user/.cache/huggingface/hub
  videoqna-reranking:
    image: ${REGISTRY:-opea}/reranking-videoqna:${TAG:-latest}
    container_name: videoqna-reranking-videoqna-server
    ports:
      - "8000:8000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      CHUNK_DURATION: ${CHUNK_DURATION}
      FILE_SERVER_ENDPOINT: ${DATAPREP_GET_FILE_ENDPOINT}
      DATAPREP_GET_VIDEO_LIST_ENDPOINT: ${DATAPREP_GET_VIDEO_LIST_ENDPOINT}
    restart: unless-stopped
  videoqna-lvm-video-llama:
    image: ghcr.io/huggingface/text-generation-inference:2.3.1-rocm
    container_name: videoqna-lvm-video-llama
    ports:
      - "${VIDEOQNA_LVM_SERVICE_PORT:-9009}:80"
    volumes:
      - "/var/lib/GenAI/videoqna/data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TGI_LLM_ENDPOINT: ${VIDEOQNA_LVM_ENDPOINT}
      HUGGING_FACE_HUB_TOKEN: ${VIDEOQNA_HUGGINGFACEHUB_API_TOKEN}
      HUGGINGFACEHUB_API_TOKEN: ${VIDEOQNA_HUGGINGFACEHUB_API_TOKEN}
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/:/dev/dri/
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
    ipc: host
    command: --model-id DAMO-NLP-SG/Video-LLaMA
  videoqna-lvm:
    image: ${REGISTRY:-opea}/lvm-video-llama:${TAG:-latest}
    container_name: videoqna-lvm-video-llama
    ports:
      - "9000:9000"
    ipc: host
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      LVM_ENDPOINT: ${LVM_ENDPOINT}
    restart: unless-stopped
    depends_on:
      - lvm-video-llama
  videoqna-backend-server:
    image: ${REGISTRY:-opea}/videoqna:${TAG:-latest}
    container_name: videoqna-backend-server
    depends_on:
      - videoqna-vdms-vector-db
      - videoqna-dataprep
      - videoqna-embedding
      - videoqna-retriever
      - videoqna-reranking
      - videoqna-lvm-video-llama
      - videoqna-lvm
    ports:
      - "8888:8888"
    entrypoint: sh -c 'sleep 45 && python videoqna.py'
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      MEGA_SERVICE_HOST_IP: ${MEGA_SERVICE_HOST_IP}
      EMBEDDING_SERVICE_HOST_IP: ${EMBEDDING_SERVICE_HOST_IP}
      RETRIEVER_SERVICE_HOST_IP: ${RETRIEVER_SERVICE_HOST_IP}
      RERANK_SERVICE_HOST_IP: ${RERANK_SERVICE_HOST_IP}
      LVM_SERVICE_HOST_IP: ${LVM_SERVICE_HOST_IP}
    ipc: host
    restart: always
  videoqna-ui-server:
    image: ${REGISTRY:-opea}/videoqna-ui:${TAG:-latest}
    container_name: videoqna-ui-server
    depends_on:
      - videoqna-backend-server
    ports:
      - "5173:5173"
    environment:
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
      no_proxy: ${no_proxy}
      BACKEND_SERVICE_ENDPOINT: ${BACKEND_SERVICE_ENDPOINT}
      BACKEND_HEALTH_CHECK_ENDPOINT: ${BACKEND_HEALTH_CHECK_ENDPOINT}
    ipc: host
    restart: always
volumes:
  videoqna-llama-model:
    external: true
networks:
  default:
    driver: bridge
