# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  faqgen:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      context: ../
      dockerfile: ./Dockerfile
    image: ${REGISTRY:-opea}/faqgen:${TAG:-latest}
  faqgen-ui:
    build:
      context: ../ui
      dockerfile: ./docker/Dockerfile
    extends: faqgen
    image: ${REGISTRY:-opea}/faqgen-ui:${TAG:-latest}
  faqgen-react-ui:
    build:
      args:
        BACKEND_SERVICE_ENDPOINT: $FAQGEN_BACKEND_ENDPOINT
      context: ../ui
      dockerfile: ./docker/Dockerfile.react
    extends: faqgen
    image: ${REGISTRY:-opea}/faqgen-react-ui:${TAG:-latest}
  llm-faqgen:
    build:
      context: GenAIComps
      dockerfile: comps/llms/src/faq-generation/Dockerfile
    extends: faqgen
    image: ${REGISTRY:-opea}/llm-faqgen:${TAG:-latest}
  vllm-rocm:
    build:
      context: GenAIComps
      dockerfile: comps/third_parties/vllm/src/Dockerfile.amd_gpu
    image: ${REGISTRY:-opea}/vllm-rocm:${TAG:-latest}
