# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  neo4j-apoc:
    image: neo4j:latest
    container_name: neo4j-apoc
    ports:
      - "${NEO4J_PORT1:-7474}:7474"
      - "${NEO4J_PORT2:-7687}:7687"
    volumes:
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/config:/config
      - ./data/neo4j/data:/data
      - ./data/neo4j/plugins:/plugins
    ipc: host
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\*
      - NEO4J_server_bolt_advertised__address=${HOST_IP}:${NEO4J_PORT2}
    restart: always

  tei-embedding-serving:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: tei-embedding-serving
    entrypoint: /bin/sh -c "apt-get update && apt-get install -y curl && text-embeddings-router --json-output --model-id ${EMBEDDING_MODEL_ID} --auto-truncate"
    ports:
      - "${TEI_EMBEDDER_PORT:-12000}:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      host_ip: ${host_ip}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}

  vllm-service:
    image: ${REGISTRY:-opea}/vllm-rocm:${TAG:-latest}
    container_name: vllm-service
    ports:
      - "${VLLM_SERVICE_PORT:-8081}:8011"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      WILM_USE_TRITON_FLASH_ATTENTION: 0
      PYTORCH_JIT: 0
    volumes:
      - "${HF_CACHE_DIR:-./data}:/data"
    shm_size: 20G
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/:/dev/dri/
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
      - apparmor=unconfined
    command: "--model ${LLM_MODEL_ID} --swap-space 16 --disable-log-requests --dtype float16 --tensor-parallel-size 1 --host 0.0.0.0 --port 8011 --num-scheduler-steps 1 --distributed-executor-backend \"mp\""
    ipc: host

  dataprep-neo4j-llamaindex:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-neo4j-llamaindex
    depends_on:
      - neo4j-apoc
      - tei-embedding-serving
    ports:
      - "${DATAPREP_PORT:-11103}:5000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      host_ip: ${host_ip}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_NEO4J_LLAMAINDEX"
      NEO4J_URL: ${NEO4J_URL}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      LLM_ENDPOINT: ${LLM_ENDPOINT}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
#      OPENAI_API_KEY: ${OPENAI_API_KEY}
#      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL}
#      OPENAI_LLM_MODEL: ${OPENAI_LLM_MODEL}
#      EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      LOGFLAG: ${LOGFLAG:-False}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      MAX_INPUT_TOKENS: ${MAX_INPUT_TOKENS:-4096}
    restart: unless-stopped

  retriever-neo4j:
    image: ${REGISTRY:-opea}/retriever:${TAG:-latest}
    container_name: retriever-neo4j
    ports:
      - "${RETRIEVER_PORT:-7000}:7000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      LOGFLAG: ${LOGFLAG:-False}
      RETRIEVER_COMPONENT_NAME: ${RETRIEVER_COMPONENT_NAME:-OPEA_RETRIEVER_NEO4J}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      LLM_ENDPOINT: ${LLM_ENDPOINT}
      EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_URL: ${NEO4J_URI}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      VDMS_USE_CLIP: 0
      host_ip: ${HOST_IP}
    depends_on:
      - neo4j-apoc
      - tei-embedding-serving

  graphrag-backend-server:
    image: ${REGISTRY:-opea}/graphrag:${TAG:-latest}
    container_name: graphrag-backend-server
    depends_on:
      - neo4j-apoc
      - tei-embedding-serving
      - retriever-neo4j
      - vllm-service
    ports:
      - "${MEGA_SERVICE_PORT:-8888}:8888"
    environment:
      no_proxy: ${no_proxy}
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
      MEGA_SERVICE_HOST_IP: ${HOST_IP}
      RETRIEVER_SERVICE_HOST_IP: ${HOST_IP}
      RETRIEVER_SERVICE_PORT: ${RETRIEVER_PORT}
      LLM_SERVER_HOST_IP: ${HOST_IP}
      LLM_SERVER_PORT: ${VLLM_SERVICE_PORT}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      LOGFLAG: ${LOGFLAG:-False}
    ipc: host
    restart: always

  graphrag-ui-server:
    image: ${REGISTRY:-opea}/graphrag-ui:${TAG:-latest}
    container_name: graphrag-ui-server
    depends_on:
      - graphrag-backend-server
    ports:
      - "${FRONTEND_SERVICE_PORT:-5173}:5173"
    environment:
      no_proxy: ${no_proxy}
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
    ipc: host
    restart: always

  nginx-server:
    image: ${REGISTRY:-opea}/nginx:${TAG:-latest}
    container_name: nginx-server
    depends_on:
      - graphrag-backend-server
      - graphrag-ui-server
    ports:
      - "${NGINX_PORT:-80}:80"
    environment:
      no_proxy: ${no_proxy}
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
      FRONTEND_SERVICE_IP: ${HOST_IP}
      FRONTEND_SERVICE_PORT: ${FRONTEND_SERVICE_PORT}
      BACKEND_SERVICE_NAME: graphrag
      BACKEND_SERVICE_IP: ${HOST_IP}
      BACKEND_SERVICE_PORT: ${MEGA_SERVICE_PORT}
      DATAPREP_SERVICE_IP: ${HOST_IP}
      DATAPREP_SERVICE_PORT: ${DATAPREP_PORT}
    ipc: host
    restart: always
networks:
  default:
    driver: bridge
